### ISSUE TITLE
Create default config & metadata files

### ISSUE THREAD

**Issue by Broderick-Westrope** [Broderick-Westrope/barber#4]
The following defaults should be used when initialising a new collection and resetting an existing collection:

Collection Config (`.barber.toml`):
```toml
# Collection Configuration

# Git version control options
[git]
auto_commit = true
```

Collection Metadata (`.barber.yaml`):
```yaml
# Collection Metadata

# List of snippets in the collection
snippets:
```

App Config (`.barber.toml`):
```toml
# App Configuration

default_collection = "./default_collection"

# Git version control options
[git]
auto_init = true
auto_commit = true
```

For now, these should all be hardcoded templates. The collection config will eventually be constructed using the defaults set in the app config, however that is out of this tickets scope.
